development:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  template: template0
  database: rdtestsite_development

test:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  template: template0
  database: rdtestsite_test
  min_messages: WARNING

# production:
#   <<: *default
#   database: db/production.sqlite3
